---
name: deploy-marketing

on:
  push:
    branches:
      - master
    paths:
      - 'packages/marketing/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/marketing/**'
defaults:
  run:
    working-directory: packages/marketing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        env:
          HUSKY: ${{ env.HUSKY }}
          HUSKY_SKIP_INSTALL: ${{ env.HUSKY_SKIP_INSTALL }}
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ env.PRODUCTION_DOMAIN }}
      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.S3_BUCKET_NAME}}/marketing/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
